## 원-핫 인코딩(One-Hot Encoding)
- 단어 집합의 크기를 벡터 차원으로 하고, 표현하고 싶은 단어의 인덱스에 1을, 나머지에는 0을 부여하는 방법
- 단어의 갯수가 늘어날수록 공간이 계속 늘어나고, 단어의 유사도를 표현못하는 한계 존재

In [1]:
import nltk
nltk.download('punkt')

c:\Users\0627j\anaconda3\envs\NLP\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
c:\Users\0627j\anaconda3\envs\NLP\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidanc

True

In [2]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize('I was wondering if anyone out there could enlighten me on this car.')
print(tokens)

word_to_index = {word: index for index, word in enumerate(tokens)}
print('단어 집합:', word_to_index)

def one_hot_encoding(word, word_to_index):
    one_hot_vector = [0] * (len(word_to_index))
    index = word_to_index[word]
    one_hot_vector[index] = 1
    return one_hot_vector

print("could", one_hot_encoding("could", word_to_index))

['I', 'was', 'wondering', 'if', 'anyone', 'out', 'there', 'could', 'enlighten', 'me', 'on', 'this', 'car', '.']
단어 집합: {'I': 0, 'was': 1, 'wondering': 2, 'if': 3, 'anyone': 4, 'out': 5, 'there': 6, 'could': 7, 'enlighten': 8, 'me': 9, 'on': 10, 'this': 11, 'car': 12, '.': 13}
could [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]


In [3]:
# Keras를 사용
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text = 'I was wondering if anyone out there could enlighten me on this car.'
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
print('단어 집합:', tokenizer.word_index)

sub_text = 'anyone out there could enlighten me'
encoded = tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

one_hot = to_categorical(encoded)
print(one_hot)

단어 집합: {'i': 1, 'was': 2, 'wondering': 3, 'if': 4, 'anyone': 5, 'out': 6, 'there': 7, 'could': 8, 'enlighten': 9, 'me': 10, 'on': 11, 'this': 12, 'car': 13}
[5, 6, 7, 8, 9, 10]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
